# -*- coding: utf-8 -*-
"""EDA ON SUPERSTORE

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KeOkaWgNdxEqsndTtJ3uu-jkxFSOM6fp

STEP 1- IMPORTING LIBRARIES INTO WORKSPACE
"""

#importing standard libraries
import numpy as np
import pandas as pd
import seaborn as sbs
import matplotlib.pyplot as plt
import plotly.express as px
import scipy.stats as stats

"""STEP 2- IMPORTING DATASET INTO THE WORKSPACE"""

pr=pd.read_csv('/content/SampleSuperstore.csv')
pr.head()

"""EXPLORATORY DATA ANALYSIS


"""

#Checking the shape of the data
pr.shape
print(f"Dataset have {pr.shape[0]} rows and {pr.shape[1]} features")

#displaying features
pr.columns

#statistical measurements
pr.describe()

"""Here max profit on a single scale is 8399.976000

"""

# we use info() to get the information on the data we were working on and it helps us to know the data type of every feature
pr.info()

"""Checking null values"""

#to check the null values in the data set we will use isnull()
pr.isnull()

"""we can state that there are no null values in the given data"""

# checking the unique values
pr.nunique()

"""By the above reference we can make the following data
SHIP MODE-Standard,second,first class and same day
Various cat in products- Office supplies,furniture,Technology
All products are delivered in among 49 states in 531 different cities
Region of services are East,west,south and central

DATA VISUALISATION
"""

#finding correlations
correlation=pr.corr()
correlation

"""Using seaborn for creating simple heatmap"""

sbs.heatmap(correlation,annot=True)
plt.show()

"""We can see that there is positive correlation between sales and profits ie. if sales increases profits also increases

Getting into more depth to understand clearly we can use graphs

Checking outliers using boxplot
"""

sbs.boxplot(data=pr)

"""There are no outliers

Depicting in bar graph
"""

pr['Category'].value_counts().plot(kind="bar")

"""The sales in the office supplies is much higher when compared to other two ie- furniture,Technology

Now visualizing the same data in different categories under each segment
"""

pd.crosstab(pr['Segment'],pr['Category']).plot(kind="bar",stacked=True)

"""Distribution for sales"""

sbs.displot(pr["Sales"])

"""Now plotting pairwise realtionship in the data set"""

sbs.pairplot(pr)

"""From the above graph we can see that profit vs sale graph it is not compulsory that if sales increases profits also increases
2.from discount vs profit graph upto 0.3 there is profit but after that the loss is occuring
3.And from discount vs sales graph we can see as discount increases the sales are decreasing

PLOTTING SUB CAT VIA BAR GRAPH
"""

pr['Sub-Category'].value_counts().plot(kind="bar")

"""The above graph is arranged as from most selling to the least selling products"""

pd.crosstab(pr["Region"],pr["Category"],pr["Profit"],aggfunc='sum').plot(kind="bar",stacked=True)

pd.crosstab(index=pr["Category"],columns=pr["Segment"],values=pr["Profit"],aggfunc="sum").plot(kind="bar",stacked=True)

"""The technology sector has the more profit under purchasing ie-consumer sector"""

pd.crosstab(index=pr["Category"],columns=pr["Ship Mode"],values=pr["Profit"],aggfunc="sum").plot(kind="bar",stacked=True)

"""Based on the following graph we can say that ship mode has profits when it is standard class and the profit is negligible when the ship is on sameday"""

plt.figure(figsize=(21,8))
sbs.countplot(x=pr['Sub-Category'])
print(pr['Sub-Category'].value_counts())

"""Highest Sold sub category is Binders and lowest Sold sub category is copiers"""

sbs.lmplot(x="Profit",y="Sales",data=pr,fit_reg=False,col="Category")
plt.show()

"""Profit is very low in furniture sector but it is also high in technology sector"""

plt.figure(figsize=(21,8))
sbs.countplot(x="Sub-Category",hue="Region",data=pr)
print(pr["Profit"].value_counts())

plt.figure(figsize=(21,8))
sbs.countplot(x="Sub-Category",hue="Segment",data=pr)

"""Now creating a bar graph with all combined sub categories with respect to the profit"""

fig,axs=plt.subplots(1,1,figsize=(19,6))
sbs.barplot("Sub-Category","Profit",data=pr)

"""This bar graph depicts the loss of each sub-category with repect to others and whereas copiers has more profit compared to the ohter sub-categories

"""

fig=px.sunburst(pr,path=['Country','Category','Sub-Category'],values='Sales',color='Category',hover_data=['Sales','Quantity','Profit'])
fig.update_layout(height=700)
fig.show()

"""**THE FINAL INSIGHTS OF THE PROJECT**

1.We can see the profits until the discount is at 0.3 percent but if the discount increases beyond 0.3 loss will occur

2.Technology sector is recorded as the highest profit sector under which the profits has come more from the consumer segment

3.There is a huge loss from the furniture sector

4.Although copiers is the least selling sub-category but it recorded more profits compared to other sub-categories

5.More profits can be recored from the east and west regions

6.The profits are high when the ship mode is in standard class and at the same time it is negligible when it is on same day

RECOMMENDED SUGGESTION

1.Discount should not be increased beyond 0.3 percent

2.As more of the loss is coming from the furniture sectore the company can stop selling furnitures

3.The shipping charges should be increased if it is on sameday

4.It should focus more on technology sector
"""